#
###################################
# Site wide configuration
####################################
#
title: Young Rok Kim
email: rok0810@gmail.com 
description: Works
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://rokoroku.github.io

#
###################################
# Jekyll configuration
####################################
#
markdown:  kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Young Rok Kim
  avatar: avatar.jpg
  job: Android/iOS Developer
  bio: ""
  email: rok0810@gmail.com
  disqus-shortname: rokoroku
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-44044751-5
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rokoroku
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
